# Generated by Django 2.0.1 on 2018-01-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Ass',
        ),
    ]
