# Generated by Django 2.0.1 on 2018-01-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180125_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ass',
            new_name='Subscriber',
        ),
    ]
